# Generated by Django 4.2.3 on 2023-08-14 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2023, 8, 14, 10, 2, 49, 848414, tzinfo=datetime.timezone.utc)),
        ),
    ]
